### ISSUE TITLE
she/her pronoun links to inactive web app

### ISSUE THREAD

**Issue by machawk1** [ablwr/ashleyblewer_com#2]
The link on your homepage with the anchor text "she/her" under the pronouns section results in a page with the Heroku template indicating that the web app is no longer running.

![heroku](https://user-images.githubusercontent.com/2514780/212358796-206a134f-884f-4c25-9f76-ca1a9db84d9a.png)

**Comment by ablwr** [comment]
oh, bummer! I'll remove it for now, assuming the site isn't coming back

**Comment by ablwr** [comment]
thanks for helping keep my site healthy!
